FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt #no cache dir prevents pip caching which results in a smaller image 

COPY . .

CMD ["gunicorn", "FinancesProject.wsgi:application", "--bind", "0.0.0.0:8000"]