apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
  namespace: webapp
spec:
  replicas: {{.Values.depl.replicas}}
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue-coiner
          image: {{.Values.depl.image}}
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "/api" #edit
