apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.backendSecret.DJANGO_SECRET_KEY }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.backendSecret.DJANGO_ALLOWED_HOSTS }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.backendSecret.CORS_ALLOWED_ORIGINS }}"
