apiVersion: v1
kind: Service
metadata:
  name: django-backend-stable
spec:
  type: ClusterIP
  selector:
    app: django-backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend-canary
spec:
  type: ClusterIP
  selector:
    app: django-backend
  ports:
    - port: 8000
      targetPort: 8000
