depl:
  image: 844586871941.dkr.ecr.us-east-1.amazonaws.com/coiner-ecr:backend-374b544d134807ce57ed792b52868da8c5f78a14
  replicas: 2

  cpuReq: 100m
  memoryReq: 256Mi
  cpuLim: 500m
  memoryLim: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPU: 70

backendSecret:
  DJANGO_SECRET_KEY: "*5!b1h!(_7y1%8*w+stns0=_zvl+#%1w-%zgir5!)=6t5h2huh"
  DJANGO_ALLOWED_HOSTS: "http://k8s-default-albingre-d956df7538-563218621.us-east-1.elb.amazonaws.com" #edit
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,http://k8s-default-albingre-d956df7538-563218621.us-east-1.elb.amazonaws.com" #edit

