depl:
  image: 844586871941.dkr.ecr.us-east-1.amazonaws.com/coiner-ecr:backend-5329183928cab224b717ac4e59d179eb49e51414
  replicas: 2

  cpuReq: 100m
  memoryReq: 256Mi
  cpuLim: 500m
  memoryLim: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPU: 70

backendSecret:
  DJANGO_SECRET_KEY: "secret_key"
  DJANGO_ALLOWED_HOSTS: "http://k8s-webapp-albingre-9b8ec7c124-1720660507.us-east-1.elb.amazonaws.com" #edit
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,http://k8s-webapp-albingre-9b8ec7c124-1720660507.us-east-1.elb.amazonaws.com" #edit

