depl:
  image: 844586871941.dkr.ecr.us-east-1.amazonaws.com/coiner-ecr:backend-v1.04 #edit
  replicas: 2
  cpuReq: 100m
  memoryReq: 256Mi
  cpuLim: 500m
  memoryLim: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPU: 70

backendSecret:
  DJANGO_SECRET_KEY: "*5!b1h!(_7y1%8*w+stns0=_zvl+#%1w-%zgir5!)=6t5h2huh"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,k8s-default-albingre-d956df7538-266143196.us-east-1.elb.amazonaws.com" #edit
  DB_NAME: "coiner"
  DB_USER: "adminuser"
  DB_PASSWORD: "r5#6QD%fnlYeBttf" #edit
  DB_HOST: "terraform-20260207103107830500000014.cqxa4s0mq11y.us-east-1.rds.amazonaws.com" #edit
  DB_PORT: "5432"
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,http://k8s-default-albingre-d956df7538-266143196.us-east-1.elb.amazonaws.com" #edit

